default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: saint_bernard_development

test:
  <<: *default
  database: saint_bernard_test

production:
  <<: *default
  database: saint_bernard_production

staging:
  <<: *default
  database: saint_bernard_production

demo:
  <<: *default
  database: saint_bernard_demo
